name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Add steps for any necessary setup, like installing dependencies
    - name: Build
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U twine
        python -m pip install -U wheel
        python3 -m pip install build==1.0.3 # pin build
        rm -rf ./build
        rm -rf ./dist/*
        python setup.py sdist bdist_wheel

    - name: Publish package on PyPI
      uses: pypa/gh-action-pypi-publish@v1.6.4
      with:
        user: __token__
        password: "${{ secrets.PYPI_TOKEN }}"
        packages_dir: ./python/dist/